"""empty message

Revision ID: 115bd16c70d5
Revises: 580b1baecd51
Create Date: 2016-03-22 14:34:14.166706

"""

# revision identifiers, used by Alembic.
revision = '115bd16c70d5'
down_revision = '580b1baecd51'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('small_image_url', sa.String(length=64), nullable=True))
    op.add_column('item', sa.Column('thumbnail_cache', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item') as batch_op:
        batch_op.drop_column('small_image_url')
        batch_op.drop_column('thumbnail_cache')
    ### end Alembic commands ###
