"""added more shoes dec 2019

Revision ID: 13c7241d70b5
Revises: db74a5d334d
Create Date: 2019-12-11 20:57:16.229032

"""

# revision identifiers, used by Alembic.
revision = '13c7241d70b5'
down_revision = 'db74a5d334d'

from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date, and_


def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
        column('model', String),
        column('brand_id', Integer),
        column('gender_id', Integer),
        column('small_image_url', String),
        column('medium_image_url', String),
        column('type', String)
    )
    # 12|butora|US
    op.bulk_insert(item_table,
        [
            {'model':'gomi seagrass', 'brand_id':'12', 'gender_id':'3', 'type':'rock'},
            {'model':'gomi pink', 'brand_id':'12', 'gender_id':'3', 'type':'rock'},
            {'model':'acro comp black', 'brand_id':'12', 'gender_id':'3', 'type':'rock'},
            {'model':'acro comp pink', 'brand_id':'12', 'gender_id':'3', 'type':'rock'}
        ]
    )
    # 2|five ten|US
    op.bulk_insert(item_table,
        [
            {'model':'dragon vcs', 'brand_id':'2', 'gender_id':'1', 'type':'rock'},
            {'model':'asym', 'brand_id':'2', 'gender_id':'1', 'type':'rock'},
            {'model':'asym', 'brand_id':'2', 'gender_id':'2', 'type':'rock'},


        ]
    )
    # 1|evolv|US
    op.bulk_insert(item_table,
        [
            {'model':'phantom', 'brand_id':'1', 'gender_id':'3', 'type':'rock'},
        ]
    )    
    # Red Chili Shoe List
    op.bulk_insert(item_table,
        [
            {'model':'voltage 2', 'brand_id':'9', 'gender_id':'1', 'type':'rock'},
        ]
    )
    # 5|scarpa|UK
    op.bulk_insert(
        item_table, [
            {'model': 'furia air', 'brand_id': '5', 'gender_id': '1', 'type': 'rock'},
        ]
    )
    # so ill Shoe List
    op.bulk_insert(item_table,
        [
            {'model':'free range pro', 'brand_id':'25', 'gender_id':'3', 'type':'rock'},
            {'model':'momoa pro', 'brand_id':'25', 'gender_id':'1', 'type':'rock'},
            {'model':'momoa pro lv', 'brand_id':'25', 'gender_id':'2', 'type':'rock'},


        ]
    )   
    # 7|tenaya|US
    op.bulk_insert(item_table,
        [
            {'model':'mastia', 'brand_id':'7', 'gender_id':'3', 'type':'rock'}
        ]
    )             


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
