"""empty message

Revision ID: 245a11a7da11
Revises: bf75fb264d9
Create Date: 2017-02-20 20:51:46.072322

"""

# revision identifiers, used by Alembic.
revision = '245a11a7da11'
down_revision = 'bf75fb264d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('offer_url', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'offer_url')
    ### end Alembic commands ###
