"""by skill stats

Revision ID: 25f6396a7cc8
Revises: df3aaf3b633c
Create Date: 2020-02-08 16:13:25.708570

"""

# revision identifiers, used by Alembic.
revision = '25f6396a7cc8'
down_revision = 'df3aaf3b633c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('average_rating_advanced_climbers', sa.String(length=64), nullable=True))
    op.add_column('item', sa.Column('average_rating_beginner_climbers', sa.String(length=64), nullable=True))
    op.add_column('item', sa.Column('average_rating_expert_climbers', sa.String(length=64), nullable=True))
    op.add_column('item', sa.Column('count_advanced_climbers', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('count_beginner_climbers', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('count_expert_climbers', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'count_expert_climbers')
    op.drop_column('item', 'count_beginner_climbers')
    op.drop_column('item', 'count_advanced_climbers')
    op.drop_column('item', 'average_rating_expert_climbers')
    op.drop_column('item', 'average_rating_beginner_climbers')
    op.drop_column('item', 'average_rating_advanced_climbers')
    # ### end Alembic commands ###
