"""empty message

Revision ID: 2826f9a4da2a
Revises: 35c6ceb8a0cb
Create Date: 2016-03-17 10:23:31.413126

"""

# revision identifiers, used by Alembic.
revision = '2826f9a4da2a'
down_revision = '35c6ceb8a0cb'

from sqlalchemy.sql import table, column
from sqlalchemy import String
from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand', sa.Column('sizing', sa.String(length=64), nullable=False, server_default='US'))

    brand = table('brand',
        column('name', String),
        column('sizing', String),
    )

    op.execute(
        brand.update().\
            where(brand.c.name=='la sportiva').\
            values({'sizing':'EUR'})
            )
    op.execute(
        brand.update().\
            where(brand.c.name=='scarpa').\
            values({'sizing':'EUR'})
            )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand') as batch_op:
        batch_op.drop_column('sizing')
    ### end Alembic commands ###
