"""user street shoe size

Revision ID: 29898fb1475e
Revises: 1d128d241d84
Create Date: 2016-04-12 14:54:14.912213

"""

# revision identifiers, used by Alembic.
revision = '29898fb1475e'
down_revision = '1d128d241d84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('street_shoe_size_in', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'street_shoe_size_in')
    ### end Alembic commands ###
