"""added popular foot shape

Revision ID: 2b94d3703c46
Revises: 32b1502c688d
Create Date: 2019-07-28 21:09:17.749672

"""

# revision identifiers, used by Alembic.
revision = '2b94d3703c46'
down_revision = '32b1502c688d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('popular_fit_descriptor', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'popular_fit_descriptor')
    ### end Alembic commands ###
