"""empty message

Revision ID: 2c284207967d
Revises: 29898fb1475e
Create Date: 2016-04-14 08:49:44.809190

"""

# revision identifiers, used by Alembic.
revision = '2c284207967d'
down_revision = '29898fb1475e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_item', sa.Column('fit', sa.Integer(), server_default="2"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item') as batch_op:
        batch_op.drop_column('fit')
    ### end Alembic commands ###
