"""added user climbing skill

Revision ID: 2fbb33e99560
Revises: 4a20f1abdea
Create Date: 2018-09-21 20:40:26.710451

"""

# revision identifiers, used by Alembic.
revision = '2fbb33e99560'
down_revision = '4a20f1abdea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('climbing_boulder', sa.Integer(),
                                    nullable=False, server_default="0"))
    op.add_column('user', sa.Column('climbing_sport', sa.Integer(),
                                    nullable=False, server_default="0"))
    op.add_column('user', sa.Column('climbing_trad', sa.Integer(),
                                    nullable=False, server_default="0"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('climbing_trad')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('climbing_sport')
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('climbing_boulder')
    ### end Alembic commands ###
