"""add date to comments

Revision ID: 44dd67063089
Revises: 53d262a01b02
Create Date: 2024-05-01 21:12:59.895275

"""

# revision identifiers, used by Alembic.
revision = '44dd67063089'
down_revision = '53d262a01b02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_item', sa.Column('comments_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_item', 'comments_date')
    # ### end Alembic commands ###
