"""item type column

Revision ID: 492e42f91c6f
Revises: 2c284207967d
Create Date: 2016-04-28 16:03:18.538732

"""

# revision identifiers, used by Alembic.
revision = '492e42f91c6f'
down_revision = '2c284207967d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('type', sa.String(length=64), server_default='rock', nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item') as batch_op:
        batch_op.drop_column('type')
    ### end Alembic commands ###
