"""empty message

Revision ID: 4c6234f36920
Revises: 49f59716a36a
Create Date: 2016-04-30 17:29:15.235615

"""

# revision identifiers, used by Alembic.
revision = '4c6234f36920'
down_revision = '49f59716a36a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('medium_image_url', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item') as batch_op:
        batch_op.drop_column('medium_image_url')

    ### end Alembic commands ###
