"""new shoes jan-2024

Revision ID: 53d262a01b02
Revises: 209f4d78ef0b
Create Date: 2024-01-03 13:18:23.415472

"""

# revision identifiers, used by Alembic.
revision = '53d262a01b02'
down_revision = '209f4d78ef0b'

from alembic import op
import sqlalchemy as sa

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer

def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
                        column('model', String),
                        column('brand_id', Integer),
                        column('gender_id', Integer),
                        column('small_image_url', String),
                        column('medium_image_url', String),
                        column('type', String)
                        )  

    # 14|Ocun|EUR
    op.bulk_insert(item_table,
        [
            {'model':'fury', 'brand_id':'14', 'gender_id':'3'},
            {'model':'sigma', 'brand_id':'14', 'gender_id':'3'},
            {'model':'havoc', 'brand_id':'14', 'gender_id':'3'},
            {'model':'jett crack', 'brand_id':'14', 'gender_id':'3'},
            {'model':'jett qc', 'brand_id':'14', 'gender_id':'3'},
            {'model':'jett lu', 'brand_id':'14', 'gender_id':'3'},
            {'model':'advancer qc', 'brand_id':'14', 'gender_id':'3'},
            {'model':'advancer lu', 'brand_id':'14', 'gender_id':'3'},
            {'model':'striker qc', 'brand_id':'14', 'gender_id':'3'},
            {'model':'striker lu', 'brand_id':'14', 'gender_id':'3'},
        ]
    )      


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
