"""empty message

Revision ID: 580b1baecd51
Revises: 2826f9a4da2a
Create Date: 2016-03-18 20:28:02.967177

"""

# revision identifiers, used by Alembic.
revision = '580b1baecd51'
down_revision = '2826f9a4da2a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('date_last_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('date_last_login')
        batch_op.drop_column('date_created')
    ### end Alembic commands ###
