"""remove model fields

Revision ID: 5b457d997e86
Revises: 61f81ce2ee02
Create Date: 2025-04-18 21:30:42.197508

"""

# revision identifiers, used by Alembic.
revision = '5b457d997e86'
down_revision = '61f81ce2ee02'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'offer_url')
    op.drop_column('item', 'asin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('asin', sa.VARCHAR(length=64), nullable=True))
    op.add_column('item', sa.Column('offer_url', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
