"""new shoes april-2025

Revision ID: 61f81ce2ee02
Revises: 1047db5fdc34
Create Date: 2025-04-08 19:58:42.271726

"""

# revision identifiers, used by Alembic.
revision = '61f81ce2ee02'
down_revision = '1047db5fdc34'

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer

def upgrade():
    # brand 32 garra
    brand_table = table('brand', 
                        column('name', String)
                        )
    op.bulk_insert(brand_table,
                   [
                       {'name': 'garra'},
                   ]
                   )
    
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
                        column('model', String),
                        column('brand_id', Integer),
                        column('gender_id', Integer),
                        column('small_image_url', String),
                        column('medium_image_url', String),
                        column('type', String)
                        )  

    # 3|LaSportiva|EUR
    op.bulk_insert(item_table,
        [
            {'model':'katana lace', 'brand_id':'3', 'gender_id':'2'},
            {'model':'ondra comp', 'brand_id':'3', 'gender_id':'3'},
            {'model':'mandala', 'brand_id':'3', 'gender_id':'3'},
            {'model':'tc extreme', 'brand_id':'3', 'gender_id':'3'},
        ]
    )

    # 28|unparallel|US
    op.bulk_insert(
        item_table, [
            {'model': 'qubit', 'brand_id': '28', 'gender_id': '3'},
            {'model': 'qubit lv', 'brand_id': '28', 'gender_id': '3'},
        ]
    )

    # 32|garra|eur
    op.bulk_insert(
        item_table, [
            {'model': 'kime', 'brand_id': '32', 'gender_id': '3'},
            {'model': 'kamae', 'brand_id': '32', 'gender_id': '3'},
            {'model': 'kokoro', 'brand_id': '32', 'gender_id': '3'},
            {'model': 'sensei', 'brand_id': '32', 'gender_id': '3'},
            {'model': 'unkai', 'brand_id': '32', 'gender_id': '3'},
        ]
    )

    # 6|boreal|US
    op.bulk_insert(item_table,
        [
            {'model':'joker', 'brand_id':'6', 'gender_id':'2'}
        ]
    )    

    # 1|evolv|US
    op.bulk_insert(
        item_table, [
            {'model': 'v6', 'brand_id': '1', 'gender_id': '3'},  
            {'model': 'v6 lv', 'brand_id': '1', 'gender_id': '3'},     
            {'model':'geshido', 'brand_id':'1', 'gender_id':'2'},
        ])  

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
