"""added new la sportiva shoes march 2020

Revision ID: 6c37817cfdf7
Revises: 7eb96261c5db
Create Date: 2020-03-08 20:11:54.527008

"""

# revision identifiers, used by Alembic.
revision = '6c37817cfdf7'
down_revision = '7eb96261c5db'

from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date

def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
                       column('model', String),
                       column('brand_id', Integer),
                       column('gender_id', Integer),
                       column('small_image_url', String),
                       column('medium_image_url', String),
                       column('type', String)
                       )

    # 3|la sportiva|EUR
    op.bulk_insert(
        item_table, [
            {'model': 'cobra 499', 'brand_id': '3',
                'gender_id': '3', 'type': 'rock'},
            {'model': 'solution comp', 'brand_id': '3',
                'gender_id': '2', 'type': 'rock'},
            {'model': 'solution comp', 'brand_id': '3',
                'gender_id': '1', 'type': 'rock'},
            {'model': 'theory', 'brand_id': '3',
                'gender_id': '2', 'type': 'rock'},
            {'model': 'theory', 'brand_id': '3',
                'gender_id': '1', 'type': 'rock'}                
        ]) 

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
