"""added scarpa shoes Feb 2020

Revision ID: 7eb96261c5db
Revises: 25f6396a7cc8
Create Date: 2020-02-25 18:47:50.258412

"""

# revision identifiers, used by Alembic.
revision = '7eb96261c5db'
down_revision = '25f6396a7cc8'

from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
                       column('model', String),
                       column('brand_id', Integer),
                       column('gender_id', Integer),
                       column('small_image_url', String),
                       column('medium_image_url', String),
                       column('type', String)
                       )
    # 5|scarpa|US
    op.bulk_insert(
        item_table, [
            {'model': 'arpia', 'brand_id': '5',
                'gender_id': '2', 'type': 'rock'},
            {'model': 'veloce', 'brand_id': '5',
                'gender_id': '2', 'type': 'rock'},
            {'model': 'veloce', 'brand_id': '5',
                'gender_id': '1', 'type': 'rock'},
            {'model': 'ribelle hd', 'brand_id': '5',
                'gender_id': '2', 'type': 'mountain'},
            {'model': 'ribelle hd', 'brand_id': '5',
                'gender_id': '1', 'type': 'mountain'}                
        ]) 

    # 2|five ten|US
    op.bulk_insert(
        item_table, [
            {'model': 'hornet', 'brand_id': '2',
                'gender_id': '1', 'type': 'rock'}              
        ])                               


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
