"""added user token

Revision ID: 9a98673423a
Revises: 1bca6839bca7
Create Date: 2018-11-08 18:58:23.398299

"""

# revision identifiers, used by Alembic.
revision = '9a98673423a'
down_revision = '1bca6839bca7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    ### end Alembic commands ###
