"""add shoes change butora shoes Aug 2025

Revision ID: ac7c34404571
Revises: 5b457d997e86
Create Date: 2025-07-31 20:14:04.829299

"""

# revision identifiers, used by Alembic.
revision = 'ac7c34404571'
down_revision = '5b457d997e86'

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer

def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
        column('model', String),
        column('brand_id', Integer),
        column('gender_id', Integer),
        column('type', String)
    )

    # change habara blue to 'habara markless'
    op.execute(
        item_table.update().\
            where(item_table.c.model=='habara blue').\
            values({'model':'habara markless'})
            )

    # Add more butora shoes
    op.bulk_insert(item_table,
        [
            {'model':'advance', 'brand_id':'12', 'gender_id':'3'},
        ]
    )

    # change reflex  to 'reflex v'
    op.execute(
        item_table.update().\
            where(item_table.c.model=='reflex').\
            values({'model':'reflex v'})
            )
    
    # Scarpa Rock Shoe List
    op.bulk_insert(item_table,
        [
            {'model':'reflex vs', 'brand_id':'5', 'gender_id':'1'},
            {'model':'reflex vs', 'brand_id':'5', 'gender_id':'2'},
        ]
    )
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
