"""empty message

Revision ID: bf75fb264d9
Revises: 3ee30f43b758
Create Date: 2017-02-20 20:38:15.722473

"""

# revision identifiers, used by Alembic.
revision = 'bf75fb264d9'
down_revision = '3ee30f43b758'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('asin', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'asin')
    ### end Alembic commands ###
