"""added new shoes June 2020

Revision ID: d22ed20e87f2
Revises: 6c37817cfdf7
Create Date: 2020-06-29 20:02:14.977941

"""

# revision identifiers, used by Alembic.
revision = 'd22ed20e87f2'
down_revision = '6c37817cfdf7'

from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
                       column('model', String),
                       column('brand_id', Integer),
                       column('gender_id', Integer),
                       column('small_image_url', String),
                       column('medium_image_url', String),
                       column('type', String)
                       )
    # 1|evolv|US
    op.bulk_insert(
        item_table, [
            {'model': 'phantom', 'brand_id': '1',
                'gender_id': '3', 'type': 'rock'},
        ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
