"""remove duplicate phantom shoe

Revision ID: d8e25eebb627
Revises: d22ed20e87f2
Create Date: 2020-07-04 09:16:58.252379

"""

# revision identifiers, used by Alembic.
revision = 'd8e25eebb627'
down_revision = 'd22ed20e87f2'

from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date, and_


def upgrade():
    item_table = table('item',
        column('id', Integer),
        column('model', String),
        column('brand_id', Integer),
        column('gender_id', Integer),
        column('medium_image_url', String),
        column('small_image_url', String)
    )

    op.execute(
        item_table.delete().\
            where(and_(item_table.c.model == 'phantom', item_table.c.gender_id == '3', item_table.c.id == 854 ))
            )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
