"""added average rating

Revision ID: da82b2787ad
Revises: 2763a5981eb8
Create Date: 2019-07-28 18:24:51.995607

"""

# revision identifiers, used by Alembic.
revision = 'da82b2787ad'
down_revision = '2763a5981eb8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('average_rating', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'average_rating')
    ### end Alembic commands ###
