"""Added shoes Feb 2021-2

Revision ID: dca9b5eea4e8
Revises: 53759f7c9f55
Create Date: 2021-02-12 17:24:13.762226

"""

# revision identifiers, used by Alembic.
revision = 'dca9b5eea4e8'
down_revision = '53759f7c9f55'

from alembic import op
import sqlalchemy as sa
from datetime import date
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date

def upgrade():
    # Create an ad-hoc table to use for the insert statement.
    item_table = table('item',
                       column('model', String),
                       column('brand_id', Integer),
                       column('gender_id', Integer),
                       column('small_image_url', String),
                       column('medium_image_url', String),
                       column('type', String)
                       )
    # 7|tenaya|US
    op.bulk_insert(
        item_table, [
            {'model': 'ra woman', 'brand_id': '7',
                'gender_id': '2', 'type': 'rock'},
            {'model': 'oasi lv', 'brand_id': '7',
                'gender_id': '3', 'type': 'rock'},
            {'model': 'aqua plus', 'brand_id': '7',
                'gender_id': '3', 'type': 'rock'},
        ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
