"""highes rated foot shape

Revision ID: df3aaf3b633c
Revises: 0e8657ab3cbf
Create Date: 2020-02-08 09:22:55.351639

"""

# revision identifiers, used by Alembic.
revision = 'df3aaf3b633c'
down_revision = '0e8657ab3cbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('highest_rated_foot_shape', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'highest_rated_foot_shape')
    # ### end Alembic commands ###
