"""made size and size_in be required

Revision ID: efb8320781d
Revises: 2b94d3703c46
Create Date: 2019-10-30 22:34:37.628962

"""

# revision identifiers, used by Alembic.
revision = 'efb8320781d'
down_revision = '2b94d3703c46'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('user_item') as batch_op:
        batch_op.alter_column('size',
                existing_type=sa.INTEGER(),
                nullable=False)
        batch_op.alter_column('size_in',
                existing_type=sa.VARCHAR(length=64),
                nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_item') as batch_op:

        batch_op.alter_column('size_in',
                existing_type=sa.VARCHAR(length=64),
                nullable=True)
        batch_op.alter_column('size',
                existing_type=sa.INTEGER(),
                nullable=True)
    ### end Alembic commands ###
